图结构是算法学中最强大的框架之一。

图是各种关系的节点和边的集合，节点是与对象对应的顶点，边是对象之间的连接。

SciPy 提供了 scipy.sparse.csgraph 模块来处理图结构。

邻接矩阵
邻接矩阵（Adjacency Matrix）是表示顶点之间相邻关系的矩阵。

邻接矩阵逻辑结构分为两部分：V 和 E 集合，其中，V 是顶点，E 是边，边有时会有权重，表示节点之间的连接强度。

连接组件
查看所有连接组件使用 connected_components() 方法。

在 scipy 库中，connected_components 函数用于分析稀疏图的连通分量。它的完整函数签名为 scipy.sparse.csgraph.connected_components(csgraph, directed=True, connection='weak', return_labels=True)。

csgraph 是一个 N x N 矩阵，表示压缩稀疏图。输入的 csgraph 将被转换为 CSR 格式进行计算。

directed 是一个可选的布尔值。如果为 True（默认），则对有向图进行操作：仅沿着 csgraph[i, j] 的路径从点 i 移动到点 j。如果为 False，则在无向图上查找最短路径：算法可以沿着 csgraph[i, j] 或 csgraph[j, i] 从点 i 进行到点 j。

connection 是一个可选的字符串，取值为 ‘weak’ 或 ‘strong’。对于有向图，使用连接类型。如果从 i 到 j 和从 j 到 i 都存在路径，则节点 i 和 j 强连通。如果将有向图的所有有向边替换为无向边会产生一个连通的（无向）图，则有向图弱连通。如果 directed == False，则不引用此关键字。

return_labels 是一个可选的布尔值。如果为 True（默认），则返回每个连通分量的标签。

该函数返回两个值：n_components 和 labels。其中，n_components 是连通分量的数量，而 labels 是长度为 N 的数组，表示连通分量的标签1。

在这个例子中，n_components 的值为2，表示图中有两个连通分量。labels 数组的长度与图中节点数相同，每个元素表示对应节点所属的连通分量的标签。在这个例子中，labels 的值为 [0, 0, 0, 1, 1]，表示节点 0、1 和 2 属于一个连通分量（标记为 0），而节点 3 和 4 属于另一个连通分量（标记为 1）。

In [1]:
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix

arr=np.array([
  [0, 1, 1, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0]
])
newarr=csr_matrix(arr)
print(connected_components(newarr))

(2, array([0, 0, 0, 1, 1]))


Dijkstra -- 最短路径算法
Dijkstra(迪杰斯特拉)最短路径算法，用于计算一个节点到其他所有节点的最短路径。

Scipy 使用 dijkstra() 方法来计算一个元素到其他元素的最短路径。

dijkstra() 方法可以设置以下几个参数：

return_predecessors: 布尔值，设置 True，遍历所有路径，如果不想遍历所有路径可以设置为 False。

indices: 元素的索引，返回该元素的所有路径。

limit: 路径的最大权重。

In [3]:
from scipy.sparse.csgraph import dijkstra
arr=np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr=csr_matrix(arr)
# return_predecessors=True 表示返回前驱节点数组
# indices=0 表示从节点 0 开始计算最短路径。
print(dijkstra(newarr,return_predecessors=True,indices=0))
"""
这段代码的输出是一个元组，包含两个数组。
第一个数组表示从节点 0 到其他节点的最短距离，
第二个数组表示从节点 0 到其他节点的最短路径上的前驱节点。
前驱节点数组表示从节点 0 到节点 1 的最短路径上的前驱节点为节点 0，
从节点 0 到节点 2 的最短路径上的前驱节点也为节点 0。
"""

(array([0., 1., 2.]), array([-9999,     0,     0]))


In [3]:
from scipy.sparse.csgraph import dijkstra
arr = np.array([
    [0, 3, 1, 0],
    [3, 0, 0, 2],
    [1, 0, 0, 4],
    [0, 2, 4, 0]
])

newarr = csr_matrix(arr)
distances, predecessors = dijkstra(newarr, return_predecessors=True, indices=0)

print(distances)
print(predecessors)

[0. 3. 1. 5.]
[-9999     0     0     2]


Floyd Warshall -- 弗洛伊德算法
弗洛伊德算法算法是解决任意两点间的最短路径的一种算法。

Scipy 使用 floyd_warshall() 方法来查找所有元素对之间的最短路径。

In [6]:
import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)
distances, predecessors = floyd_warshall(newarr, return_predecessors=True)
"""
第一个矩阵与之前的例子相同，表示图中所有节点对之间的最短距离。
第二个矩阵表示图中所有节点对之间最短路径上的前驱节点。"""

print(distances)
print(predecessors)

[[0. 1. 2.]
 [1. 0. 3.]
 [2. 3. 0.]]
[[-9999     0     0]
 [    1 -9999     0]
 [    2     0 -9999]]


In [5]:
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import floyd_warshall

arr = np.array([
    [0, 3, 1, 0],
    [3, 0, 0, 2],
    [1, 0, 0, 4],
    [0, 2, 4, 0]
])

newarr = csr_matrix(arr)
distances = floyd_warshall(newarr)

print(distances)

[[0. 3. 1. 5.]
 [3. 0. 4. 2.]
 [1. 4. 0. 4.]
 [5. 2. 4. 0.]]


Bellman Ford -- 贝尔曼-福特算法
贝尔曼-福特算法是解决任意两点间的最短路径的一种算法。

Scipy 使用 bellman_ford() 方法来查找所有元素对之间的最短路径，通常可以在任何图中使用，包括有向图、带负权边的图

bellman_ford 是 scipy.sparse.csgraph 模块中的一个函数，用于计算给定图中单源最短路径。它使用 Bellman-Ford 算法实现，时间复杂度为 O(VE)，其中 V 是图中节点的数量，E 是图中边的数量。

与 dijkstra 函数不同，bellman_ford 函数能够处理带有负权边的图。如果图中存在负环（即总权值为负数的环），则dijkstra算法将引发异常。

在图论中，边的权值通常表示从一点到另一点的距离、花费或时间。在大多数情况下，边的权值都是非负的，因为距离、花费和时间通常都是非负的。

然而，在某些情况下，边的权值可能是负数。例如，在金融领域，边的权值可能表示投资回报率，这个回报率可能是负数。在这种情况下，图中就会出现带有负权边的情况。

带有负权边的图在计算最短路径时会更加复杂。一些最短路径算法（如 Dijkstra 算法）无法处理带有负权边的图。而其他一些算法（如 Bellman-Ford 算法）能够处理带有负权边的图，但如果图中存在负环（即总权值为负数的环），则算法将引发异常。

在实际应用中，如果图中存在负环，则需要检查数据是否正确，并尝试修正数据以消除负环。如果负环是合理的，则需要重新审视问题，看看是否可以通过其他方式解决。

In [7]:
import numpy as np
from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix

arr = np.array([
  [0, -1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(bellman_ford(newarr, return_predecessors=True, indices=0))

(array([ 0., -1.,  2.]), array([-9999,     0,     0]))


In [8]:
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import bellman_ford

arr = np.array([
    [0, -1, 2],
    [0, 0, 3],
    [0, 0, 0]
])

newarr = csr_matrix(arr)
distances, predecessors = bellman_ford(newarr, return_predecessors=True, indices=0)

print(distances)
print(predecessors)

[ 0. -1.  2.]
[-9999     0     0]


深度优先顺序
depth_first_order() 方法从一个节点返回深度优先遍历的顺序。

可以接收以下参数：

图
图开始遍历的元素

In [9]:
import numpy as np
from scipy.sparse.csgraph import depth_first_order
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 0, 1],
  [1, 1, 1, 1],
  [2, 1, 1, 0],
  [0, 1, 0, 1]
])

newarr = csr_matrix(arr)

print(depth_first_order(newarr, 1))
"""
这段代码的输出是两个数组。第一个数组表示遍历的顺序，第二个数组表示每个节点的父节点。
"""

(array([1, 0, 3, 2]), array([    1, -9999,     1,     0]))


广度优先顺序
breadth_first_order() 方法从一个节点返回广度优先遍历的顺序。

可以接收以下参数：

图
图开始遍历的元素



In [10]:
import numpy as np
from scipy.sparse.csgraph import breadth_first_order
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 0, 1],
  [1, 1, 1, 1],
  [2, 1, 1, 0],
  [0, 1, 0, 1]
])

newarr = csr_matrix(arr)

print(breadth_first_order(newarr, 1))
"""
它返回两个数组：第一个数组表示遍历的顺序，第二个数组表示每个节点的父节点。"""

(array([1, 0, 2, 3]), array([    1, -9999,     1,     1]))
